## NUMPY AND VISUALIZATION

In [1]:
import numpy as np

In [2]:
l=[1,2,3,4]

In [3]:
arr=np.array(l)

In [4]:
arr

array([1, 2, 3, 4])

In [6]:
type(arr)

numpy.ndarray

In [13]:
##For 2D array
np.array([[1,2,3,4],[5,6,7,8]])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
l=[1,2,3,4]

In [15]:
##For matrix
np.matrix(l)

matrix([[1, 2, 3, 4]])

In [16]:
b=[1,2,3,4]

In [17]:
##another mathod
np.asanyarray(b)

array([1, 2, 3, 4])

In [18]:
l=[1,2,3,4]

In [19]:
a=np.array(l)

In [20]:
##copy
c=a

In [21]:
a

array([1, 2, 3, 4])

In [22]:
c

array([1, 2, 3, 4])

In [23]:
##indexing method also work
c[0]=100

In [24]:
c

array([100,   2,   3,   4])

In [25]:
a

array([100,   2,   3,   4])

In [26]:
##copy but does not work indexing mathod
d=np.copy(a)

In [27]:
d

array([100,   2,   3,   4])

In [28]:
a

array([100,   2,   3,   4])

In [29]:
a[1]=200

In [30]:
a

array([100, 200,   3,   4])

In [31]:
d

array([100,   2,   3,   4])

In [34]:
np.fromfunction( lambda i,j: i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [35]:
np.fromfunction( lambda i,j: i+j,(3,3))

array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.]])

In [36]:
np.fromstring('234 234',sep=" ")

array([234., 234.])

### NUMPY DATATYPE

In [37]:
l=[3,4,5,6]

In [38]:
## 1D array
arr=np.array(l)

In [39]:
arr

array([3, 4, 5, 6])

In [40]:
arr.ndim

1

In [42]:
##2D arrray
arr2=np.array([[3,4,5],[6,7,8]])

In [43]:
arr2

array([[3, 4, 5],
       [6, 7, 8]])

In [44]:
arr2.ndim

2

In [45]:
arr2.size

6

In [46]:
arr2.shape

(2, 3)

In [48]:
arr2.dtype

dtype('int64')

In [50]:
## TO create an array of 10 valuse b/w 1 to 5
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [52]:
##zero matrix
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [53]:
np.arange(2.3,4.5,5)

array([2.3])

In [54]:
## 4 into 2 matix
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [56]:
np.ones(4)

array([1., 1., 1., 1.])

In [58]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [63]:
on=np.ones((2,3,4))

In [64]:
on

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [65]:
on*5

array([[[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]],

       [[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]]])

In [66]:
np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [67]:
##Diagonal element are one
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [70]:
##Standard natural daviation
arr=np.random.rand(3,4)

In [73]:
arr

array([[0.1378648 , 0.22176082, 0.09773523, 0.381344  ],
       [0.33818603, 0.45820949, 0.81627729, 0.81122548],
       [0.78638471, 0.47203521, 0.06213594, 0.42493831]])

In [71]:
import pandas as pd

In [72]:
pd.DataFrame(arr)

0         1         2         3
0  0.137865  0.221761  0.097735  0.381344
1  0.338186  0.458209  0.816277  0.811225
2  0.786385  0.472035  0.062136  0.424938

In [74]:
type(arr)

numpy.ndarray

In [75]:
##For reshape the array
arr1=arr.reshape(4,3)

In [76]:
arr1

array([[0.1378648 , 0.22176082, 0.09773523],
       [0.381344  , 0.33818603, 0.45820949],
       [0.81627729, 0.81122548, 0.78638471],
       [0.47203521, 0.06213594, 0.42493831]])

In [77]:
arr1[1][0]

0.3813440035886506

In [80]:
arr=np.random.randint(1,100,(5,5))

In [81]:
arr

array([[ 8, 86, 31, 74, 36],
       [44, 91, 57, 86, 13],
       [36, 56, 13,  9, 25],
       [76, 91, 11, 23, 96],
       [67, 37,  6,  6, 85]])

In [82]:
arr[2:4,[1,2]]

array([[56, 13],
       [91, 11]])

In [83]:
##indexing also possible
arr[0][0]=500

In [84]:
arr

array([[500,  86,  31,  74,  36],
       [ 44,  91,  57,  86,  13],
       [ 36,  56,  13,   9,  25],
       [ 76,  91,  11,  23,  96],
       [ 67,  37,   6,   6,  85]])

##Matrix operation

In [85]:
arr1=np.random.randint(1,3,(3,3))
arr2=np.random.randint(1,3,(3,3))

In [90]:
arr1

array([[1, 1, 2],
       [2, 2, 2],
       [1, 2, 2]])

In [91]:
arr2

array([[2, 2, 1],
       [1, 1, 2],
       [1, 2, 2]])

In [86]:
##Matrix  addition

In [87]:
arr1+arr2

array([[3, 3, 3],
       [3, 3, 4],
       [2, 4, 4]])

In [88]:
## matrix substraction
arr1-arr2

array([[-1, -1,  1],
       [ 1,  1,  0],
       [ 0,  0,  0]])

In [89]:
arr1*arr2

array([[2, 2, 2],
       [2, 2, 4],
       [1, 4, 4]])

In [92]:
## Matrix multiplication
arr1@arr2

array([[ 5,  7,  7],
       [ 8, 10, 10],
       [ 6,  8,  9]])

In [5]:
arr=np.zeros((4,4))

In [6]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
row=np.array([1,2,3,4])

In [8]:
row

array([1, 2, 3, 4])

In [9]:
arr=arr+row

In [58]:
arr

array(['sudh', 'kumar'], dtype='<U5')

In [59]:
## For transpose
arr.T

array(['sudh', 'kumar'], dtype='<U5')

In [12]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [1.        , 1.41421356, 1.73205081, 2.        ],
       [1.        , 1.41421356, 1.73205081, 2.        ],
       [1.        , 1.41421356, 1.73205081, 2.        ]])

In [14]:
np.exp(arr)

array([[ 2.71828183,  7.3890561 , 20.08553692, 54.59815003],
       [ 2.71828183,  7.3890561 , 20.08553692, 54.59815003],
       [ 2.71828183,  7.3890561 , 20.08553692, 54.59815003],
       [ 2.71828183,  7.3890561 , 20.08553692, 54.59815003]])

##Numpy Array Manipulation

In [17]:
arr=np.random.randint(1,10,(3,4))

In [18]:
arr

array([[8, 8, 5, 5],
       [7, 6, 4, 5],
       [3, 9, 6, 6]])

In [19]:
##For reshape operation
arr.reshape(2,6)

array([[8, 8, 5, 5, 7, 6],
       [4, 5, 3, 9, 6, 6]])

In [20]:
arr1=np.array([1,2,3,4])

In [21]:
arr1

array([1, 2, 3, 4])

In [22]:
arr1.ndim

1

##Numpy string Function

In [52]:
arr=np.array(["sudh","kumar"])

In [53]:
arr

array(['sudh', 'kumar'], dtype='<U5')

In [54]:
## FOR uppercase
np.char.upper(arr)

array(['SUDH', 'KUMAR'], dtype='<U5')

In [55]:
## For lowercae
np.char.lower(arr)

array(['sudh', 'kumar'], dtype='<U5')

In [56]:
##Make fisrt word in uppercase
np.char.title(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [57]:
np.char.capitalize(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [33]:
arr1=np.random.randint(1,10,(3,4))

In [34]:
arr1

array([[1, 5, 4, 8],
       [4, 9, 7, 7],
       [8, 6, 4, 1]])

In [35]:
## sin value
np.sin(arr1)

array([[ 0.84147098, -0.95892427, -0.7568025 ,  0.98935825],
       [-0.7568025 ,  0.41211849,  0.6569866 ,  0.6569866 ],
       [ 0.98935825, -0.2794155 , -0.7568025 ,  0.84147098]])

In [36]:
## cos falue
np.cos(arr1)


array([[ 0.54030231,  0.28366219, -0.65364362, -0.14550003],
       [-0.65364362, -0.91113026,  0.75390225,  0.75390225],
       [-0.14550003,  0.96017029, -0.65364362,  0.54030231]])

In [37]:
## tan value
np.tanh(arr1)

array([[0.76159416, 0.9999092 , 0.9993293 , 0.99999977],
       [0.9993293 , 0.99999997, 0.99999834, 0.99999834],
       [0.99999977, 0.99998771, 0.9993293 , 0.76159416]])

In [38]:
##log value
np.log10(arr1)

array([[0.        , 0.69897   , 0.60205999, 0.90308999],
       [0.60205999, 0.95424251, 0.84509804, 0.84509804],
       [0.90308999, 0.77815125, 0.60205999, 0.        ]])

In [39]:
## for mean
np.mean(arr1)

5.333333333333333

In [40]:
##For median
np.median(arr1)

5.5

In [41]:
## For varience
np.var(arr1)

6.388888888888889

In [42]:
##For max value in arr1
np.max(arr1)

9

In [43]:
####For min value in arr1
np.min(arr1)

1

##Linear Algebra

In [47]:
arr=np.array([9,5,8,3,2])

In [48]:
arr

array([9, 5, 8, 3, 2])

In [50]:
##For sorting
np.sort(arr)

array([2, 3, 5, 8, 9])

##Numpy Matrix Library

In [63]:
import numpy.matlib as nm

In [64]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [65]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [78]:
arr4=np.random.randint([[2,3],[4,5]])


In [79]:
arr5=np.random.randint([[5,3],[2,5]])

In [80]:
arr4

array([[0, 1],
       [1, 3]])

In [81]:
arr5

array([[3, 0],
       [0, 4]])

In [77]:
##Multiplication for elem
np.dot(arr4,arr5)


array([[1, 4],
       [0, 0]])